const { Converter } = require('showdown')
const showdownToc = require('showdown-toc')
const { writeFileSync, readFileSync } = require('fs')
const converter = new Converter({ ghCompatibleHeaderId: true, headerLevelStart: 2, extensions: [showdownToc()] })
const md = readFileSync('public/recipes.md')
const content = converter.makeHtml('# Sommaire\n[toc]\n' + md)
const html = (readFileSync('src/page.html') + '').replace('{content}', content).replace('{nbLines}', 8)
writeFileSync('public/index.html', html)
